### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by tm1000** [psalm/psalm-vscode-plugin#47]
### Features

- [X] Fix settings pane to be more graphical
- [X] Mock StreamWriter so that logging of output from language server actually logs in verbose mode
- [X] Fix #30 to not blow up because of https://github.com/vimeo/psalm/pull/6007
- [X] Add setting to "Index" workspace (Just calls same method as in #30 for now)
- [X] Add support for `onSave`, `onOpen`, `onClose` (see https://github.com/vimeo/psalm/pull/6010)
- [X] Add support for `workspace/didChangeWatchedFiles` (see https://github.com/vimeo/psalm/pull/6014) Fixes #32 
- [X] Update dependencies
- [x] Look at https://github.com/psalm/psalm-vscode-plugin/pull/36
- [x] Look at https://github.com/psalm/psalm-vscode-plugin/pull/11
- [x] Run prettier on save (vscode for this project only)
- [x] Bundle Extension using webpack (https://code.visualstudio.com/api/working-with-extensions/bundling-extension)
- [x] While running Psalm should not show status bar message (Which is useless and takes up space)

### Awaiting Upstream PRs:
- [X] https://github.com/vimeo/psalm/pull/6007 (4.9.0)
- [X] https://github.com/vimeo/psalm/pull/6012 (4.9.0)
- [x] https://github.com/vimeo/psalm/pull/6010 (4.9.0)
- [x] https://github.com/vimeo/psalm/pull/6014 (4.9.0)
- [x] https://github.com/vimeo/psalm/pull/6231 (Unreleased)
